### ISSUE TITLE
Assign Features to Developers

### ISSUE THREAD

**Issue by ninghuiker** [ninghuiker/ETI-Assignment#1]
1. Display Main Menu
2. Read and Load Maze from File
3. View Maze 
4. Play Maze Game 
5. Configure Current Maze

**Comment by ninghuiker** [comment]
Please assign the last feature to one of your developers.

**Comment by FangTingKoh** [comment]
Completed Test Cases for the MainMenu Function

[TestCase_for_MainMenuFunction.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4144776/TestCase_for_MainMenuFunction.pdf)

**Comment by zerong1** [comment]
I have already assigned to Ray for the last feature.
