### ISSUE TITLE
Validation for Main Menu

### ISSUE THREAD

**Issue by zerong1** [ninghuiker/ETI-Assignment#11]
Jansen I need you to help to do the validation on  Main Menu when the user doesn't select any options it will prompt the user to enter one of the options provided on the main menu.

**Comment by RichMuscles** [comment]
Okay, will work on it ASAP will update you when done

**Comment by RichMuscles** [comment]
Latest push bd180e1 includes new main_menu.py file and edited the code for read_and_load.py to work with it.

**Comment by RichMuscles** [comment]
completed in "bd180e1 "

**Comment by zerong1** [comment]
feature is functional
