### ISSUE TITLE
Configuration current maze 

### ISSUE THREAD

**Issue by zerong1** [ninghuiker/ETI-Assignment#16]
Ray I assigning configuration current maze function to you. Start to do once you complete your unit test for view maze.

**Comment by zerong1** [comment]
Jansen since you had done your read_and_load function I will assign you with Ray to do the last function deadline by 2/9/2020

**Comment by ninghuiker** [comment]
Full functioning configure maze is completed in commit 23e79bd.

**Comment by zerong1** [comment]
Feature is functional
