### ISSUE TITLE
Bugs issued by QA

### ISSUE THREAD

**Issue by FangTingKoh** [ninghuiker/ETI-Assignment#17]
Hello, to all developers and technical lead, please fix the errors I stated below!!

1) Input options only allow within 1-4 and not until 5. There is no option5.

Reasons: 
It is because when I input the invalid option such as inputting a letter in the option. 

The error message should display “Invalid syntax. Enter 1-4” and not “Invalid syntax. Enter 1-5”

2) Coding is not fully working for option 1 when testing the wrong data file name. 
Because it displays "Traceback  (most recent call last):  File "C:\Users\Emily\ Desktop\ETIAssignmentmaster\ETIAssignmentmaste r \main_menu.py", line 1, in  from read_and_load import *  File "C:\Users\Emily\Desktop\ ETIAssignment-master\ ETIAssignmentmaster\ read_and_load.py", line 19, in  from main_menu import * File "C:\Users\Emily\Desktop\ETIAssignmentmaster\ETIAssignment master\main_menu.py", line 37, in  mainMenu() File"C:\Users\Emily\Desktop \ ETIAssignmentmaster\ETIAss ignmentmaster \main_menu.py", line 19, in mainMenu Read_Load() File "C:\Users\Emily\Desktop \ETIAssignmentmaster\ETIAssignmentmaste r\ read_and_load.py", line 11, in  Read_Load file = open(userinput) FileNotFoundError: [Errno 2] No such file or directory: 'game.csv'” 

3) Coding is not working for input options 4. Can't display the current configuration.

**Comment by raytan24** [comment]
Fixed for Options 1-4

**Comment by raytan24** [comment]
Uploaded to my branch

**Comment by FangTingKoh** [comment]
Great!

**Comment by FangTingKoh** [comment]
Hello, to all developers and technical lead, please fix the errors I stated below!!

There are issues for option 3: 

The game maze is not moving up when I pressed the letter "W" and also it's not moving to the right when I pressed the letter "D" on the keyboard.

**Comment by FangTingKoh** [comment]
Hello, to all developers and technical lead, please fix the errors I stated below!!

For mainmenu.py
1) when entering the wrong file name such as game.csv at the “Enter the name of the data file:” 
The actual outcome display error message "please key in the name of the data file". 

However, the expected outcome should be displaying the error message " please key in the correct name of the data file "  so that the players will not get confused, whether is it the game got system error because they have already entered the name of the game file. 

For play_maze.py 
1) When I keyed in "W", the movement of the game maze unable to move UP. 
2) When I keyed in "D", the movement of the game maze unable to move RIGHT.

**Comment by FangTingKoh** [comment]
Hi to all developers and technical lead,  please fix the errors I posted on Feb 7. 

Btw, the Input options only allow within 1-4 and not until 5. There is no option5.
Reasons:
It is because when I input the invalid option such as inputting a letter in the option.

The error message should display “Invalid syntax. Enter 1-4” and not “Invalid syntax. Enter 1-5”

Thus, change the error message "Invalid syntax. Enter 1-5" to "Invalid syntax. Enter 1-4".

**Comment by zerong1** [comment]
I had fixed the error message.
The error message should display “Invalid syntax. Enter 0-4” and not “Invalid syntax. Enter 1-4” too.
0 is also an option for exiting the app. so I had changed to 0-4 instead of 1-4.

**Comment by FangTingKoh** [comment]
Issues solved for the play_maze.py

the movement for "W" is able to move UP.
the movement for "D" of the game maze is able to move RIGHT

**Comment by FangTingKoh** [comment]
Hi to all developers and technical lead, there are some changes to be made in order to make players engaging in this game.

For mainmenu.py 

1) we need to let the players know that the game can only view if the data file to load. Hence, when we input option 2 and option 3 without inputting the option 1 first. The error message should display “please enter data file for option 1 before entering option 2 for View Maze and option 3 for Play maze game” instead of keep prompting them to enter their input.

2) When players input option 4, the error message should be spelled correctly that is “option 4 is **unavailable**!” and not "option 4 is **unavaliable** . Also, I think it is better to display the main menu when prompting players to enter other options in the input so that user don’t have to scroll up again if they need to see the main menu. 
Display 
"Option 4 is unavailable!"
“Main Menu
=========
[1] Read and load maze from file
[2] View Maze
[3] Play maze game
[4] Configure current maze

[0] Exit Maze

Enter your input:”

**Comment by ninghuiker** [comment]
Hi Fangting, 

The Play Maze should be working. If it cannot move its only because the move will make A go into the "Wall" which is X. That is why it may not be working at the start of the game. Please try to make it move onto those spots with "O". 

The validation for the main menu has also been fixed and pushed.

**Comment by FangTingKoh** [comment]
Okay noted. Btw, all the bugs have been resolved! Thank you all!
