### ISSUE TITLE
Read and load from file (unit test)

### ISSUE THREAD

**Issue by zerong1** [ninghuiker/ETI-Assignment#18]
Jansen start doing your unit test now by today.

**Comment by zerong1** [comment]
jansen how the unit test going? anyway deadline by today

**Comment by RichMuscles** [comment]
Its in progress now, will be able to meet the deadline

**Comment by RichMuscles** [comment]
Unit test done. However for one i am unsure for the imports, do take a look

**Comment by RichMuscles** [comment]
Committed in 847d564

**Comment by zerong1** [comment]
Can you try figure it out too I am also trying to solve for the pytest issue

**Comment by zerong1** [comment]
Had reopened a similar issue for unit test on Read and Load function.
