### ISSUE TITLE
QA Test Cases Writeup

### ISSUE THREAD

**Issue by ninghuiker** [ninghuiker/ETI-Assignment#2]

**Comment by ninghuiker** [comment]
Please finish this up ASAP, it has been overdue by a day.

**Comment by FangTingKoh** [comment]
> Please finish this up ASAP, it has been overdue by a day.

Sorry, the Test case is done for the function of the main menu.

[Function_of_mainmenu_TestCase.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4144598/Function_of_mainmenu_TestCase.pdf)

**Comment by FangTingKoh** [comment]
Completed the Test case for MainMenu function.

[TestCase_for_MainMenuFunction.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4144782/TestCase_for_MainMenuFunction.pdf)

**Comment by FangTingKoh** [comment]
Completed TestCases for MainMenu Function.

[TestCase_for_MainMenuFunction.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4144822/TestCase_for_MainMenuFunction.pdf)

**Comment by FangTingKoh** [comment]
Complete QA Test case for test_mainmenufunction

[TestCase_for_MainMenuFunction.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4146225/TestCase_for_MainMenuFunction.pdf)

**Comment by FangTingKoh** [comment]
Updated QA Test case for test_mainmenufunction

[Updated_TestCase_for_MainMenuFunction.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4147792/Updated_TestCase_for_MainMenuFunction.pdf)

**Comment by FangTingKoh** [comment]
QA Test Cases document includes:

test_mainmenu

test_loadmazegame

test_ playmazegame

[QA_TestCases.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4155760/QA_TestCases.pdf)

**Comment by FangTingKoh** [comment]
QA Test Cases document for updating test_mainmenu

[QA_TestCases1.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4155846/QA_TestCases1.pdf)

**Comment by FangTingKoh** [comment]
QA Test Cases document includes:

main_menu.py

read_and_load.py

play_maze.py

[ManualTest_QA.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4167488/ManualTest_QA.pdf)

**Comment by FangTingKoh** [comment]
QA Test Cases document includes:

main_menu.py

read_and_load.py

play_maze.py

[ManualTest_QA.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4167720/ManualTest_QA.pdf)

**Comment by FangTingKoh** [comment]
Throwback to test all the applications developed or updated on Feb5.

[FEB5_ManualTest_QA.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4168098/FEB5_ManualTest_QA.pdf)

**Comment by FangTingKoh** [comment]
Manual Testing on the updated applications.

[FEB7_ManualTest_QA.docx](https://github.com/ninghuiker/ETI-Assignment/files/4173772/FEB7_ManualTest_QA.docx)

**Comment by FangTingKoh** [comment]
Manual Testing on the updated applications.

[FEB7_ManualTest_QA.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4173802/FEB7_ManualTest_QA.pdf)

**Comment by FangTingKoh** [comment]
finalise qa test case
[QA_Testcase_ManualTesting.pdf](https://github.com/ninghuiker/ETI-Assignment/files/4177040/QA_Testcase_ManualTesting.pdf)
