### ISSUE TITLE
Any Unit Test

### ISSUE THREAD

**Issue by ninghuiker** [ninghuiker/ETI-Assignment#21]
Have you sent any unit tests to the QA? This is already overdue.

**Comment by zerong1** [comment]
![image](https://user-images.githubusercontent.com/45195708/73762554-50468500-47ab-11ea-92ec-59d1eeb642cb.png)

Still figuring out how to fix this error

**Comment by zerong1** [comment]
[Manual unit testcase (ReadandLoad).docx](https://github.com/ninghuiker/ETI-Assignment/files/4173576/Manual.unit.testcase.ReadandLoad.docx)
[Manual unit testcase (MainMenu).docx](https://github.com/ninghuiker/ETI-Assignment/files/4173577/Manual.unit.testcase.MainMenu.docx)

**Comment by zerong1** [comment]
2 manual unit test case is done
