### ISSUE TITLE
QA Pytest

### ISSUE THREAD

**Issue by FangTingKoh** [ninghuiker/ETI-Assignment#25]
QA Pytest for test_mainmenus.py

Comment: Able to display the main menu. However, there Is still errors!

[QA_Pytest.zip](https://github.com/ninghuiker/ETI-Assignment/files/4155804/QA_Pytest.zip)

**Comment by zerong1** [comment]
Fangting all the manual unit test is done except the view maze Ray will send it to you. I had already push it to the master branch.

**Comment by FangTingKoh** [comment]
Noted, can anyone help with the pytest if no then I will switch to manual testing.

**Comment by FangTingKoh** [comment]
can anyone help with the pytest? If no, then i will switch to manual testing

**Comment by ninghuiker** [comment]
Testing is switched to manual testing and pytest will no longer be used.
