### ISSUE TITLE
Unit testing error

### ISSUE THREAD

**Issue by raytan24** [ninghuiker/ETI-Assignment#26]
Hi team , 
Error for unit testing for ViewMaze . 
Are you guys facing the same issue too?

**Comment by raytan24** [comment]
![image](https://user-images.githubusercontent.com/58837389/73805581-01780a00-4802-11ea-9284-c948a90c14d8.png)

Attached is the screenshot

**Comment by zerong1** [comment]
Yes same error. If still cannot solve by tomorrow we probably will use manual instead of automation.

**Comment by raytan24** [comment]
Okay noted

**Comment by zerong1** [comment]
Guys lets do unit manual testing i am sure you guys already know as i had already informed you(developers) on other social platforms. but i will still comment here for this issue.

**Comment by raytan24** [comment]
ok noted , manual testing it is

**Comment by zerong1** [comment]
Yes,  I will close this issue
