### ISSUE TITLE
QA Monitoring Result and Test Analysis

### ISSUE THREAD

**Issue by FangTingKoh** [ninghuiker/ETI-Assignment#29]
Hi Project Manager, please have a look at  my monitoring Result and Test Analysis

[QA_MonitoringResult_and_Analysis.xlsx](https://github.com/ninghuiker/ETI-Assignment/files/4176574/QA_MonitoringResult_and_Analysis.xlsx)

**Comment by FangTingKoh** [comment]
But this not the finalise because still got configuration maze. I'll update it once I have done with the test case. Thank you!

**Comment by ninghuiker** [comment]
Noted. Thank you.

**Comment by FangTingKoh** [comment]
The finalise monitoring result and analysis
[QA_MonitoringResult_and_Analysis.xlsx](https://github.com/ninghuiker/ETI-Assignment/files/4176991/QA_MonitoringResult_and_Analysis.xlsx)
