### ISSUE TITLE
Unit Test Cases Writeup

### ISSUE THREAD

**Issue by ninghuiker** [ninghuiker/ETI-Assignment#3]
Please send over your unit test cases to the QA once completed.

**Comment by ninghuiker** [comment]
This has been overdue by a day, please send the test cases writeup here.

**Comment by zerong1** [comment]
[Developer Test Cases.docx](https://github.com/ninghuiker/ETI-Assignment/files/4153809/Developer.Test.Cases.docx)

**Comment by zerong1** [comment]
[Manual unit testcase (MainMenu).docx](https://github.com/ninghuiker/ETI-Assignment/files/4173570/Manual.unit.testcase.MainMenu.docx)
[Manual unit testcase (ReadandLoad).docx](https://github.com/ninghuiker/ETI-Assignment/files/4173571/Manual.unit.testcase.ReadandLoad.docx)

**Comment by zerong1** [comment]
For main menu and read and load manual unit test case is done

**Comment by zerong1** [comment]
[Manual unit test for functions(switch to web layout).docx](https://github.com/ninghuiker/ETI-Assignment/files/4174585/Manual.unit.test.for.functions.switch.to.web.layout.docx)

**Comment by zerong1** [comment]
Since the configuration just implement i had to reupdate it Will get it done by today

**Comment by ninghuiker** [comment]
Noted.

**Comment by zerong1** [comment]
[Manual unit test for functions(switch to web layout and only 100% view).docx](https://github.com/ninghuiker/ETI-Assignment/files/4176623/Manual.unit.test.for.functions.switch.to.web.layout.and.only.100.view.docx)
configuration maze is completed

**Comment by zerong1** [comment]
all of these unit tests have been passed to QA

**Comment by ninghuiker** [comment]
Noted with thanks.
