### ISSUE TITLE
Set up Jenkins Connections for Test Cases

### ISSUE THREAD

**Issue by ninghuiker** [ninghuiker/ETI-Assignment#4]
Set up a connection to Jenkins so that it can be accessed for your test cases.

**Comment by ninghuiker** [comment]
Please do so ASAP, this has been overdue for a day.

**Comment by FangTingKoh** [comment]
> Please do so ASAP, this has been overdue for a day.

I am sorry but please give me time to figure out. I need time to figure out, I hope you understand...Thank you!

**Comment by FangTingKoh** [comment]
Unable to set up the Jenkins. I do not get your requirement.
I thought is PM set up, we use since pm is the one that interacts with teacher for plugin installation.
have you set it up? @ninghuiker

**Comment by ninghuiker** [comment]
The plugin installation is what I need to inform the teacher about but for the setting up of the plugins, it is not entirely my work.

**Comment by ninghuiker** [comment]
But I will take over from now.

**Comment by ninghuiker** [comment]
Connection has been established and plugin is working.
