### ISSUE TITLE
Read and Load maze from file

### ISSUE THREAD

**Issue by zerong1** [ninghuiker/ETI-Assignment#6]

**Comment by RichMuscles** [comment]
Done, Read and Load works by user inputting the file he/she desires.

**Comment by RichMuscles** [comment]
"Completed in commit 4a5dd8d"

**Comment by zerong1** [comment]
feature is functional

**Comment by RichMuscles** [comment]
completed in "bd180e1 "

**Comment by zerong1** [comment]
Unit test is not done. Try to get it done asap.

**Comment by zerong1** [comment]
Deadline will be tomorrow

**Comment by zerong1** [comment]
Completed in e9eb08a

**Comment by zerong1** [comment]
feature is functional
