### ISSUE TITLE
View Maze

### ISSUE THREAD

**Issue by zerong1** [ninghuiker/ETI-Assignment#7]

**Comment by zerong1** [comment]
Ray what is the progress of your function now?

**Comment by raytan24** [comment]
completed

**Comment by raytan24** [comment]
open from file is done but stored memory not

**Comment by zerong1** [comment]
able to get data from stored memory now

**Comment by zerong1** [comment]
feature is functional

**Comment by zerong1** [comment]
Unit test for view maze. Please try get it done asap

**Comment by zerong1** [comment]
The deadline will be tomorrow

**Comment by zerong1** [comment]
feature is functional

**Comment by zerong1** [comment]
Updating the milestone
